[Variables]
YYY=150
Jian=70

Icon1NameAndPath=#@#\icon\typora.png
HB1=#@#\icon\typora2.png
Icon1Text=Typora
LocationPath1=["C:\Program Files\Typora\Typora.exe"]

Icon2NameAndPath=#@#\icon\TIM.png
HB2=#@#\icon\tim2.png
Icon2Text=TIM
LocationPath2=["C:\Program Files (x86)\Tencent\TIM\Bin\TIM.exe"]

Icon3NameAndPath=#@#\icon\Vscode.png
HB3=#@#\icon\vscode2.png
Icon3Text=Vscode
LocationPath3=["C:\Users\Administrator.USER-20181202TV\AppData\Local\Programs\Microsoft VS Code\Code.exe"]

Icon4NameAndPath=#@#\icon\wechat.png
HB4=#@#\icon\weixin.png
Icon4Text=WeChat
LocationPath4=["D:\WeChat\WeChat.exe"]

Icon5NameAndPath=#@#\icon\ssr.jpg
HB5=#@#\icon\ssr.png
Icon5Text=SSTap
LocationPath5=["C:\Users\Administrator.USER-20181202TV\AppData\Local\SSTap-beta\SSTap.exe"]

Icon6NameAndPath=#@#\icon\everything.jpg
HB6=#@#\icon\everything2.png
Icon6Text=Everything
LocationPath6=["C:\Program Files\Everything\Everything.exe"]

Icon7NameAndPath=#@#\icon\Google.png
HB7=#@#\icon\chrome.png
Icon7Text=Chrome
LocationPath7=["C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"]